version: '3.5'

# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx

services:
  app:
    image: azizsuf/deep-dark-sea-prod:latest
    container_name: deep_dark_sea_prod
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 --chdir /app/flaskr wsgi:app
    environment:
      - MYSQL_HOST=$ENV_MYSQL_HOST
      - MYSQL_DATABASE=$ENV_MYSQL_DATABASE
      - MYSQL_USER=$ENV_MYSQL_USER
      - MYSQL_PASSWORD=$ENV_MYSQL_PASSWORD
    expose:
    - 5000
    restart: unless-stopped

  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_USER=$ENV_MYSQL_USER
      - MYSQL_ROOT_PASSWORD=$ENV_MYSQL_PASSWORD
      - MYSQL_DATABASE=$ENV_MYSQL_DATABASE
    volumes:
      - ~/mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


