version: '3.5'

services:
  app:
    image: azizsuf/DeepDarkSea:latest
    container_name: deep_dark_sea
    command: python -m flask --app /app/flaskr/main run --host=0.0.0.0
    ports:
      - 80:5000
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ~/mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

