name: Deploy-to-prod
env:
  APP_WORKDIR: /root/app
  DOCHUB_APP_REPO: deep-dark-sea-prod

on:
  workflow_dispatch:

jobs:
  ci_part:
    name: Push to DockerHub
    runs-on: ubuntu-22.04

    steps:
      - name: Clone a git repository
        uses: actions/checkout@v3
      
      - name: Cut commit sha
        id: cut
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        
      - name: Log into DockerHUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCHUB_USERNAME }}
          password: ${{ secrets.DOCHUB_PASSWORD }}
          
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCHUB_USERNAME }}/${{ env.DOCHUB_APP_REPO }}:latest #${{ steps.cut.outputs.sha_short }}
      
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash

  cd_part:
    name: Update the docker-image on the server
    runs-on: ubuntu-22.04
    needs: [ci_part]

    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_SERVER_HOSTNAME }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PROD_SERVER_SSH_PORT }}
          script: |
            cd ${{ env.APP_WORKDIR }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
