name: Lint Python
on:
  - push
  - pull_request

jobs:
  lint_python:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone a git repository
        uses: actions/checkout@v3
      - name: Run flake8 linter
        uses: cclauss/Find-Python-syntax-errors-action@master